import streamlit as st
import pandas as pd
import numpy as np

# Internal modules
from data import db
from ui import components, styles, charts
from llm.multi_agent_review import is_available as llm_review_available, review_stock_sync

# -------------------------------------------------------------
# App Configuration & SEO Best Practices
# -------------------------------------------------------------
st.set_page_config(
    page_title="Market Scanner V2 — Overnight Data Viewer",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Inject professional V1 styling
styles.inject_custom_css()

# -------------------------------------------------------------
# Session State
# -------------------------------------------------------------
if "db_loaded" not in st.session_state:
    st.session_state.db_loaded = False
if "scan_df" not in st.session_state:
    st.session_state.scan_df = pd.DataFrame()
if "scan_raw" not in st.session_state:
    st.session_state.scan_raw = {}

# -------------------------------------------------------------
# Sidebar Configuration
# -------------------------------------------------------------
st.sidebar.title("V2 Database Viewer")
st.sidebar.markdown("This dashboard reads directly from a SQLite database generated by the nightly scanner (headless or Colab).")

db_source = st.sidebar.selectbox(
    "Database Source",
    ["Default Local Database (scans_data.db)", "Upload Custom Database (.db)"],
    key="db_source_select"
)

db_path = db.DB_PATH
db_display_name = "Default Local Database (scans_data.db)"

if db_source == "Upload Custom Database (.db)":
    uploaded_db = st.sidebar.file_uploader(
        "Upload scans_data.db",
        type=["db", "sqlite", "sqlite3"],
        key="uploaded_db_file",
        help="Upload the database file generated by your Colab or nightly scan."
    )
    if uploaded_db is not None:
        import os
        uploaded_db_path = os.path.join(os.getcwd(), "scans_data_uploaded.db")
        
        # Avoid writing the file to disk on every single rerun unless the uploaded file changed
        already_written = (
            st.session_state.get("last_uploaded_db_name") == uploaded_db.name and
            st.session_state.get("last_uploaded_db_size") == uploaded_db.size and
            os.path.exists(uploaded_db_path)
        )
        
        if not already_written:
            try:
                with open(uploaded_db_path, "wb") as f:
                    f.write(uploaded_db.getbuffer())
                st.session_state.last_uploaded_db_name = uploaded_db.name
                st.session_state.last_uploaded_db_size = uploaded_db.size
            except Exception as e:
                st.sidebar.error(f"Error saving uploaded database: {e}")
        
        db_path = uploaded_db_path
        db_display_name = f"Uploaded Database: {uploaded_db.name}"
    else:
        st.sidebar.warning("Please upload a .db file to proceed.")
        db_path = None

# Track active database path in session state to handle resets on source/file change
if "active_db_path" not in st.session_state:
    st.session_state.active_db_path = db_path
elif st.session_state.active_db_path != db_path:
    st.session_state.active_db_path = db_path
    st.session_state.db_loaded = False
    st.session_state.scan_df = pd.DataFrame()
    st.session_state.scan_raw = {}

# Compute stats if a valid path is selected
db_count = 0
db_last_updated = None
if db_path is not None:
    db_count, db_last_updated = db.get_db_stats(db_path=db_path)
    if db_count > 0:
        st.sidebar.success(
            f"**Active DB:** {db_display_name}\n\n"
            f"Contains **{db_count}** stocks.\n\n"
            f"Last Scan Run: {db_last_updated}"
        )
    else:
        st.sidebar.warning(f"Database is empty or invalid:\n{db_display_name}")

st.sidebar.markdown("---")
st.sidebar.subheader("Filter Stocks")

# Fidelity CSV upload
fidelity_file = st.sidebar.file_uploader(
    "Upload Fidelity Positions CSV",
    type=["csv"],
    key="fidelity_csv_v2",
    help="Upload your downloaded Fidelity portfolio CSV to filter results to only your holdings."
)

# Manual ticker filter
filter_tickers_input = st.sidebar.text_input(
    "Filter by Tickers (comma-separated)",
    value="",
    placeholder="e.g. AAPL, MSFT, TSLA",
    key="filter_tickers_v2"
)

asset_filter = st.sidebar.selectbox(
    "Asset class",
    ["All", "Equities", "ETFs", "Mutual funds"],
    help="Compare like with like; fund and equity scores use different evidence sets.",
)

st.sidebar.markdown("---")

if st.sidebar.button("Load Overnight Data", type="primary"):
    if db_path is None:
        st.sidebar.error("No database loaded. Please upload a database file first.")
    else:
        with st.spinner("Loading stocks from database..."):
            df = db.load_all_summaries(db_path=db_path)
            if not df.empty:
                asset_map = {"Equities": "equity", "ETFs": "etf", "Mutual funds": "mutual_fund"}
                if asset_filter in asset_map:
                    df = df[df["asset_type"] == asset_map[asset_filter]]

                invalid_histories = db.find_invalid_price_histories(db_path=db_path)
                invalid_visible = sorted(set(df["ticker"]) & set(invalid_histories))
                if invalid_visible:
                    df = df[~df["ticker"].isin(invalid_visible)]
                    st.warning(
                        f"Excluded {len(invalid_visible)} securities with suspect corporate-action or price-jump data: "
                        + ", ".join(invalid_visible)
                    )
                # Apply Fidelity CSV filter
                filter_set = set()
                if fidelity_file is not None:
                    from data.universe import parse_fidelity_positions_csv
                    parsed = parse_fidelity_positions_csv(fidelity_file)
                    if parsed:
                        filter_set.update(parsed)
                        st.sidebar.success(f"Parsed {len(parsed)} tickers from portfolio!")
                    else:
                        st.sidebar.error("Could not parse tickers from CSV.")
                
                # Apply manual ticker filter
                if filter_tickers_input.strip():
                    manual_tickers = [t.strip().upper() for t in filter_tickers_input.split(",") if t.strip()]
                    filter_set.update(manual_tickers)
                
                # Filter the dataframe if any filters are active
                if filter_set:
                    df = df[df["ticker"].isin(filter_set)]
                    if df.empty:
                        st.error(f"None of the filtered tickers ({', '.join(sorted(filter_set))}) were found in the database.")
                    else:
                        st.sidebar.info(f"Showing **{len(df)}** of {db_count} stocks matching your filter.")
                
                if not df.empty:
                    df = df.sort_values(by=["bull_score", "risk_score"], ascending=[False, True])
                    st.session_state.scan_df = df
                    
                    # Load raw data for filtered stocks (up to 50)
                    top_tickers = df["ticker"].head(50).tolist()
                    st.session_state.scan_raw = {}
                    for t in top_tickers:
                        st.session_state.scan_raw[t] = db.load_raw_data(t, db_path=db_path)
                        
                    st.session_state.db_loaded = True
            else:
                st.error("Database returned no data.")

# -------------------------------------------------------------
# Main Dashboard Layout
# -------------------------------------------------------------
components.render_header()

st.markdown("""
### Ultra-Fast Overnight Data Viewer
Welcome to V2. This viewer bypasses all heavy machine learning APIs and instantly loads the results processed by your Google Colab / Local Headless Scanner.
""")

if st.session_state.db_loaded and not st.session_state.scan_df.empty:
    df = st.session_state.scan_df
    
    # 1. Sector Heatmap (rendered if 2 or more stocks exist)
    if len(df) >= 2:
        st.markdown("### Sector Map")
        st.caption("Area represents market capitalization or fund net assets; color represents Bull Score. Hover for company identity, industry, risk, quality, and scenario details.")
        heatmap_df = df.copy()
        if 'market_cap' in heatmap_df.columns and 'marketCap' not in heatmap_df.columns:
            heatmap_df = heatmap_df.rename(columns={'market_cap': 'marketCap'})
        heatmap_fig = charts.create_sector_heatmap(heatmap_df)
        st.plotly_chart(heatmap_fig, width="stretch")
        st.markdown("### Composite Risk Score vs. Bull Score")
        st.caption("The preferred signal region is upper-left: a higher Bull Score with lower modeled risk. These are scanner scores, not probabilities or expected returns.")
        risk_fig = charts.create_risk_return_chart(heatmap_df)
        st.plotly_chart(risk_fig, width="stretch")
        
    st.markdown("---")
    
    st.markdown("### Top Candidates")
    if "bayesian_posterior" in df.columns:
        components.render_top5_upside_cards(df)
        st.markdown("---")
        
    top_bullish = df.sort_values(by=["bull_score", "risk_score"], ascending=[False, True]).head(5)
    components.render_top5_cards(top_bullish, "Top 5 Bullish (Multi-Factor)")
    st.markdown("---")
        

    # Detailed Stock View
    st.markdown("---")
    st.subheader("Detailed Security Report")
    selected_ticker = st.selectbox("Select a ticker to view full analysis:", df["ticker"].tolist())
    
    if selected_ticker:
        # Load detailed data lazily if not in RAM
        if selected_ticker not in st.session_state.scan_raw:
            with st.spinner(f"Loading deep-dive data for {selected_ticker}..."):
                st.session_state.scan_raw[selected_ticker] = db.load_raw_data(selected_ticker, db_path=db_path)
                
        details = st.session_state.scan_raw.get(selected_ticker, {})
        
        if not details:
            st.warning("Detailed data for this ticker is missing from the database.")
        else:
            scores = details.get("scores", {})
            tech = details.get("technical", {})
            price_features = details.get("price_features", {})
            fundamentals = details.get("fundamentals", {})
            options_data = details.get("options_data", {})
            
            # General Info
            col1, col2, col3 = st.columns([2, 1, 1])
            with col1:
                st.markdown(f"### {selected_ticker} — {fundamentals.get('shortName', '')}")
                st.markdown(f"**Sector:** {fundamentals.get('sector', 'N/A')} | **Industry:** {fundamentals.get('industry', 'N/A')}")
            with col2:
                st.metric("Last Price", f"${price_features.get('close', 0):,.2f}")
            with col3:
                mcap = fundamentals.get('marketCap') or fundamentals.get('totalAssets')
                mcap_str = f"${mcap/1e9:,.2f} B" if mcap and mcap >= 1e9 else f"${mcap/1e6:,.2f} M" if mcap else "N/A"
                st.metric("Net Assets" if details.get("asset_type") in {"mutual_fund", "etf"} else "Market Cap", mcap_str)
                
            st.markdown(" ")
            
            tab1, tab2, tab3 = st.tabs(["Performance & Technicals", "Causal & Fundamentals", "Raw Data"])
            
            with tab1:
                # Technical Subplots & Gauges
                chart_col, score_col = st.columns([2, 1])
                
                with chart_col:
                    if "hist" in details:
                        hist_df = details["hist"]
                        if isinstance(hist_df, pd.DataFrame) and not hist_df.empty and "Open" in hist_df.columns:
                            price_fig = charts.create_price_chart(hist_df, selected_ticker)
                            st.plotly_chart(price_fig, width="stretch")
                        else:
                            st.info("Historical price data is not available for this ticker.")
                    
                with score_col:
                    st.markdown("##### Performance Scores")
                    g_col1, g_col2 = st.columns(2)
                    with g_col1:
                        st.plotly_chart(
                            charts.create_score_gauge(scores.get("bull_score", 50), "Bull Score"),
                            width="stretch"
                        )
                    with g_col2:
                        st.plotly_chart(
                            charts.create_score_gauge(scores.get("risk_score", 50), "Risk Score (lower is better)", max_val=100, invert=True),
                            width="stretch"
                        )
                        
                    st.markdown("##### Category Breakdown")
                    components.render_category_breakdown(scores.get("category_scores", {}))
                    
                    st.markdown("##### Warnings & Risks")
                    components.render_risk_warnings(scores.get("warnings", []))
                    components.render_risk_analysis(scores.get("risk_analysis", {}))
                    
                st.markdown("---")
                
                # Options & Forecast Section
                opt_col, fcast_col = st.columns([1, 1])
                
                with opt_col:
                    st.markdown("##### Recommended Option Strategies")
                    strategies = details.get("strategies", [])
                    components.render_strategy_table(strategies)
                    
                    radar_fig = charts.create_strategy_radar(strategies)
                    st.plotly_chart(radar_fig, width="stretch")
                    
                with fcast_col:
                    st.markdown("##### Probabilistic Forecasts")
                    forecasts = details.get("forecast", {}).get("forecasts", {})
                    components.render_forecast_card(forecasts)
                    
                    fcast_fig = charts.create_forecast_chart(
                        details.get("forecast", {}).get("current_price", price_features.get('close', 0)),
                        forecasts,
                        selected_ticker
                    )
                    st.plotly_chart(fcast_fig, width="stretch")
                    
            with tab2:
                st.markdown("### Bayesian-Causal Discovery & Fundamentals")
                st.markdown("Integrates the Fidelity-style Quality Score with Structural Causal Models, Edwards & Magee Pattern Breakouts, and Bayesian Inference.")
                
                causal_col, fund_col = st.columns([1, 1])
                with causal_col:
                    components.render_causal_analysis_card(
                        details.get("causal_results", {}), 
                        details.get("bayesian_results", {}),
                        details.get("patterns", {}),
                        details.get("sentiment", {}),
                        scores.get("lookalike_stats", {}),
                        scores.get("win_rate_stats", {})
                    )
                with fund_col:
                    components.render_fundamental_screen_table(details.get("fundamental_results", {}))

                st.markdown("---")
                if st.button("Run Multi-Agent Critical Review", key=f"llm_review_{selected_ticker}"):
                    with st.spinner("Independent LLM specialists are reviewing the evidence..."):
                        st.session_state.setdefault("llm_reviews", {})[selected_ticker] = review_stock_sync(selected_ticker, details)
                if not llm_review_available():
                    st.caption("Set OPENAI_API_KEY to enable the optional LLM review layer.")
                if selected_ticker in st.session_state.get("llm_reviews", {}):
                    components.render_llm_review(st.session_state.llm_reviews[selected_ticker])

            with tab3:
                raw_col1, raw_col2 = st.columns(2)
                with raw_col1:
                    st.markdown("**Fundamentals**")
                    fund_data = {
                        "Trailing P/E": fundamentals.get("trailingPE", "N/A"),
                        "Forward P/E": fundamentals.get("forwardPE", "N/A"),
                        "PEG Ratio": fundamentals.get("pegRatio", "N/A"),
                        "Beta": fundamentals.get("beta", "N/A"),
                        "Dividend Yield": f"{fundamentals.get('dividendYield', 0)*100:.2f}%" if fundamentals.get("dividendYield") else "N/A",
                        "Revenue Growth": f"{fundamentals.get('revenueGrowth', 0)*100:.2f}%" if fundamentals.get("revenueGrowth") else "N/A",
                        "Profit Margin": f"{fundamentals.get('profitMargins', 0)*100:.2f}%" if fundamentals.get("profitMargins") else "N/A",
                    }
                    st.json(fund_data)
                    
                with raw_col2:
                    st.markdown("**Options Sentiment**")
                    opts_data = {
                        "Put/Call Vol Ratio": options_data.get("put_call_volume_ratio", "N/A"),
                        "Put/Call OI Ratio": options_data.get("put_call_oi_ratio", "N/A"),
                        "LEAPS Call/Put OI Ratio": options_data.get("leaps_call_put_oi_ratio", "N/A"),
                        "Avg Call IV": f"{options_data.get('avg_call_iv', 0)*100:.1f}%" if options_data.get("avg_call_iv") else "N/A",
                        "Avg Put IV": f"{options_data.get('avg_put_iv', 0)*100:.1f}%" if options_data.get("avg_put_iv") else "N/A",
                        "IV Term Structure (Near/Far)": options_data.get("iv_term_structure", "N/A"),
                        "Options Liquidity Score": options_data.get("options_liquidity_score", "N/A"),
                    }
                    st.json(opts_data)
else:
    st.info("Click 'Load Overnight Data' in the sidebar to populate the dashboard.")
