import streamlit as st
import pandas as pd
import numpy as np

# Internal modules
from data.universe import SECTOR_MAP
from data import db
from ui import components

# -------------------------------------------------------------
# App Configuration & SEO Best Practices
# -------------------------------------------------------------
st.set_page_config(
    page_title="Market Scanner V2 — Overnight Data Viewer",
    layout="wide",
    initial_sidebar_state="expanded"
)

# -------------------------------------------------------------
# Custom CSS
# -------------------------------------------------------------
st.markdown("""
<style>
    /* Dark Theme Core */
    :root {
        --background: #0e1117;
        --surface: #1e2532;
        --primary: #3b82f6;
        --success: #10b981;
        --danger: #ef4444;
        --warning: #f59e0b;
        --text: #f8fafc;
        --text-secondary: #94a3b8;
        --border: #334155;
    }
    
    /* Overall app styling */
    .stApp {
        background-color: var(--background);
        color: var(--text);
        font-family: 'Inter', 'Roboto', sans-serif;
    }
    
    /* General card styling */
    .metric-card {
        background-color: var(--surface);
        border: 1px solid var(--border);
        border-radius: 12px;
        padding: 1.2rem;
        transition: transform 0.2s ease, box-shadow 0.2s ease;
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
    }
    .metric-card:hover {
        transform: translateY(-2px);
        box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);
        border-color: rgba(59, 130, 246, 0.5);
    }
</style>
""", unsafe_allow_html=True)

# -------------------------------------------------------------
# Session State
# -------------------------------------------------------------
if "db_loaded" not in st.session_state:
    st.session_state.db_loaded = False
if "scan_df" not in st.session_state:
    st.session_state.scan_df = pd.DataFrame()
if "scan_raw" not in st.session_state:
    st.session_state.scan_raw = {}

# -------------------------------------------------------------
# Sidebar Configuration
# -------------------------------------------------------------
st.sidebar.title("V2 Database Viewer")
st.sidebar.markdown("This dashboard reads directly from the local SQLite database generated by the headless overnight scanner. No live API calls are made.")

db_count, db_last_updated = db.get_db_stats()
if db_count > 0:
    st.sidebar.success(f"Database contains **{db_count}** stocks.\nLast Updated: {db_last_updated}")
else:
    st.sidebar.warning("Database is empty. Please run `run_nightly_scan.py` first.")

if st.sidebar.button("Load Overnight Data", type="primary"):
    with st.spinner("Loading thousands of stocks from database..."):
        df = db.load_all_summaries()
        if not df.empty:
            df = df.sort_values(by=["bull_score", "risk_score"], ascending=[False, True])
            st.session_state.scan_df = df
            
            # Load raw data only for the top 50 to save RAM in Streamlit initially
            # Users can dynamically load more if needed, but we'll load top 50 here
            top_tickers = df["ticker"].head(50).tolist()
            st.session_state.scan_raw = {}
            for t in top_tickers:
                st.session_state.scan_raw[t] = db.load_raw_data(t)
                
            st.session_state.db_loaded = True
        else:
            st.error("Database returned no data.")

# -------------------------------------------------------------
# Main Dashboard Layout
# -------------------------------------------------------------
components.render_header()

st.markdown("""
### ⚡ Ultra-Fast Overnight Data Viewer
Welcome to V2. This viewer bypasses all heavy machine learning APIs and instantly loads the results processed by your Google Colab / Local Headless Scanner.
""")

if st.session_state.db_loaded and not st.session_state.scan_df.empty:
    df = st.session_state.scan_df
    
    st.markdown("---")
    
    # Render Top 5 Cards
    top_bullish = df.sort_values(by=["bull_score", "risk_score"], ascending=[False, True]).head(5)
    components.render_top5_cards(top_bullish, "🟢 Top 5 Bullish Candidates")
    st.markdown("<br>", unsafe_allow_html=True)
    
    # Top 5 Highest Upside (Bayesian)
    if "bayesian_posterior" in df.columns:
        components.render_top5_upside_cards(df)
        st.markdown("<br>", unsafe_allow_html=True)
        
    # Sector Heatmap
    st.subheader("Industry Sector Heatmap")
    st.markdown("Quickly identify which sectors have the strongest bullish momentum.")
    components.render_sector_heatmap(df)
    st.markdown("<br>", unsafe_allow_html=True)
    
    # Detailed Stock View
    st.markdown("---")
    st.subheader("Detailed Security Report")
    selected_ticker = st.selectbox("Select a ticker to view full analysis:", df["ticker"].tolist())
    
    if selected_ticker:
        # Load detailed data lazily if not in RAM
        if selected_ticker not in st.session_state.scan_raw:
            with st.spinner(f"Loading deep-dive data for {selected_ticker}..."):
                st.session_state.scan_raw[selected_ticker] = db.load_raw_data(selected_ticker)
                
        details = st.session_state.scan_raw.get(selected_ticker, {})
        
        if not details:
            st.warning("Detailed data for this ticker is missing from the database.")
        else:
            scores = details.get("scores", {})
            tech = details.get("technical", {})
            price_features = details.get("price_features", {})
            fundamentals = details.get("fundamentals", {})
            options_data = details.get("options_data", {})
            
            # Score Gauges
            components.render_score_gauges(scores)
            
            tabs = st.tabs(["Analysis & Technicals", "Category Breakdown", "Options Recommendations", "Forecasts"])
            
            with tabs[0]:
                causal_col, fund_col = st.columns([1, 1])
                with causal_col:
                    components.render_causal_analysis_card(
                        details.get("causal_results", {}), 
                        details.get("bayesian_results", {}), 
                        details.get("sentiment", {})
                    )
                with fund_col:
                    if "quality_score" in details.get("fundamental_results", {}):
                        components.render_fundamental_quality_card(details.get("fundamental_results", {}))
                    
                chart_col, pat_col = st.columns([2, 1])
                with chart_col:
                    if "hist" in details:
                        components.render_price_chart(selected_ticker, details["hist"])
                with pat_col:
                    components.render_patterns(details.get("patterns", []))
                    st.markdown("<br>", unsafe_allow_html=True)
                    st.markdown("**Key Indicators**")
                    rsi = tech.get("rsi", 50)
                    macd_hist = tech.get("macd_histogram", 0)
                    st.metric("RSI (14)", f"{rsi:.1f}", "Overbought" if rsi > 70 else "Oversold" if rsi < 30 else "Neutral")
                    st.metric("MACD Hist", f"{macd_hist:.2f}")

            with tabs[1]:
                components.render_category_breakdown(scores)
                
            with tabs[2]:
                strategies = details.get("strategies", [])
                components.render_options_strategies(strategies, options_data)
                
            with tabs[3]:
                forecast_data = details.get("forecast", {})
                components.render_forecast_cones(forecast_data)
else:
    st.info("Click 'Load Overnight Data' in the sidebar to populate the dashboard.")
